import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Food {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //The name of the meal
  final String name;

  //The raw weight of the meal
  final double weight;

  //The carbohydrates content of the meal
  final double carbohydrates;

  //The proteins content of the meal
  final double proteins;

  //The lipids content of the meal
  final double lipids;

  //The calories content of the meal
  final double calories;

  //When the meal occured
  final DateTime dateTime;

  //Default constructor
  Food(this.id, this.name, this.weight, this.carbohydrates, this.proteins,
      this.lipids, this.calories, this.dateTime);
}//Meal